### ISSUE TITLE
Unable to handle multiple repositories

### ISSUE THREAD

**Issue by clobrano** [samprintz/obsidian-issue-augmentation-plugin#1]
If the repository name was part of the text (e.g. `projectname#1234`) instead than a configuration setting, it would be possible to handle multiple repositories

**Comment by samprintz** [comment]
I like the idea. I'll give it a try in the next few days.

**Comment by samprintz** [comment]
I did some changes here: #2. Would you like to do some testing and check if it meets your requirements?

**Comment by clobrano** [comment]
Sure, I'll have a try. Thank you

**Comment by samprintz** [comment]
@clobrano please check if the [new release](https://github.com/samprintz/obsidian-issue-augmentation-plugin/releases/tag/0.1.0) meets your requirements.

**Comment by clobrano** [comment]
For some reason I still get 404 error when the application tries to get the issues, while `curl` is perfectly fine using the same URL :shrug: 

plugin:github-issue-augmentation:1990     GET https://api.github.com/search/issues?q=owner%3Aclobrano+repo%3Aletsdo&owner=clobrano&repo=letsdo&per_page=1&page=1 404

**Comment by samprintz** [comment]
I'm sorry, I can't reproduce, even within Obsidian and using your GitHub owner and repository name:

![20231015-143811-screenshot](https://github.com/samprintz/obsidian-issue-augmentation-plugin/assets/7581457/3e30f5a5-c6a6-4566-9dff-41e24fab9efe)

Two more guesses:

- There might be something wrong with the token? Have you already tried without specifying a token?
- Did you use the latest release (0.1.0)?
